[db]
filename = "database.db"

[discord]
support_info = "Ping {} for any questions"
rust_version_info = "latest nightly from rustup"
hw_info = "Benchmarks are run in a controlled sandbox with limited resources."
methodology = "We use criterion to benchmark. Submissions may be manually reviewed."

[docker]
container_ref = "ferris-elf-bencher"

[aoc]
inputs_dir = "inputs/"